//homepage action types
export const GET_COUNTRIES_DATA_START = 'homepage/GET_COUNTRIES_DATA_START';
export const GET_COUNTRIES_DATA_SUCCESS = 'homepage/GET_COUNTRIES_DATA_SUCCESS';
export const GET_COUNTRIES_DATA_FAILURE = 'homepage/GET_COUNTRIES_DATA_FAILURE';
